### ISSUE TITLE
Hackage homepage and source repo links are broken

### ISSUE THREAD

**Issue by MaxGabriel** [haskell-works/hw-hspec-hedgehog#3]
The links on hackage to the homepage and source repo point to https://github.com/githubuser/hw-hspec-hedgehog#readme and https://github.com/githubuser/hw-hspec-hedgehog, respectively. They should point to https://github.com/haskell-works/hw-hspec-hedgehog

**Comment by newhoggy** [comment]
Fixed by matt-keibler.  Thanks!
