### ISSUE TITLE
Allow to be built against call-stack 0.2

### ISSUE THREAD

**Issue by DanBurton** [haskell-works/hw-hspec-hedgehog#33]
Currently hw-hspec-hedgehog is constrained to `call-stack < 0.2`, but it seems to work just fine with it.

I was able to reproduce a passing build & test locally like so:

```bash
stack unpack hw-hspec-hedgehog-0.1.0.8 && cd hw-hspec-hedgehog-0.1.0.8
echo 'resolver: nightly-2019-09-30' > stack.yaml
edit hw-hspec-hedgehog.cabal  # relax the constraint on call-stack
stack build --test --bench --no-run-benchmarks --fast
```

**Comment by newhoggy** [comment]
Looks like the upper bound has already been bumped.  Closing.
